linters:
  enable-all: true
  disable:
    - scopelint
    - interfacer
    - golint
    - maligned
    - varnamelen
    - exhaustivestruct
    - gochecknoglobals
    - paralleltest
    - testpackage
    - wsl

linters-settings:
  wrapcheck:
    ignorePackageGlobs:
      - github.com/facily-tech/go-core/*
  errcheck:
    check-type-assertions: true
    check-blank: true

issues:
  fix: false
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0
  exclude-rules:
    - path: _test\.go
      linters:
        - funlen
        - lll
        - dupl
        - cyclop

run:
  timeout: 1m

# golangci.com configuration
# https://github.com/golangci/golangci/wiki/Configuration