apiVersion: v1
kind: ConfigMap
metadata:
  name: $REPO_NAME
  namespace: $NAMESPACE
data:
  ENV: '$ENV'
  DOCKER_REGISTRY: '$DOCKER_REGISTRY'
  AWS_DEFAULT_REGION: '$AWS_DEFAULT_REGION'
  NAMESPACE: '$NAMESPACE'
  DOMAIN_APPLICATION: '$DOMAIN_APPLICATION'
  CLUSTER_NAME: '$CLUSTER_NAME'
  REPO_NAME: '$REPO_NAME'
  MEMORY_REQUEST: '$MEMORY_REQUEST'
  CPU_REQUEST: '$CPU_REQUEST'
  MEMORY_LIMIT: '$MEMORY_LIMIT'
  CPU_LIMIT: '$CPU_LIMIT'
  SERVICE_CLUSTER_PORT: '$SERVICE_CLUSTER_PORT'
  DOCKER_PORT: '$DOCKER_PORT'
  # application env
  API_HOST_PORT: '$API_HOST_PORT'
  API_GRACEFUL_WAIT_TIME: '$API_GRACEFUL_WAIT_TIME'
  HTTP_CLIENT_TIMEOUT: '$HTTP_CLIENT_TIMEOUT'
  SWAGGER_URL: '$SWAGGER_URL'
  SWAGGER_HOST: '$SWAGGER_HOST'
  DD_ENV: '$ENV' # DD_ENV is the recomendation as default for DataDog, but it is the same a ENV
  DD_SERVICE: '$REPO_NAME' # DD_SERVICE is the service name, which is the same as REPO_NAME
