name: Build and Deploy - Development

on:
  workflow_dispatch:
## Deve remover o comentário abaixo para disparar o fluxo através de commits
#  push:
#    branches:
#      - develop

jobs:
  deploy_on_k8s:
    uses: facily-tech/actions-reusable-workflows/.github/workflows/deploy-backend-api-argocd.yml@v1
    with:
      ## Substituir os valores entre <>. Exemplo: Sou da tribo de core-commerce, substituir <tribe> por core-commerce
      tribe: <tribe>
      squad: <squad>
      vault-secret-path: development/<tribe/squad/service>
      environment: development
      container-port: 8080
      probe-readiness-path: /health
      probe-liveness-path: /health
      github-sha: ${{ github.sha }}
      repository-name: ${{ github.event.repository.name }}      
      application-name: ${{ github.event.repository.name }}
      application-domain: ${{ github.event.repository.name }}.development.faci.ly
    secrets:
      docker-build-extra-args: '-f build/Dockerfile'
      github-org: ${{ secrets.FACILY_ORG }}
      docker-registry: ${{ secrets.DOCKER_REGISTRY_DEVELOPMENT }}
      facily-github-token: ${{ secrets.FACILY_GITHUB_TOKEN }}
      ecr-aws-region: ${{ secrets.AWS_DEFAULT_REGION_DEVELOPMENT }}
      ecr-aws-role-to-assume: ${{ secrets.AWS_GITHUB_ROLE_DEVELOPMENT }}
      k8s-aws-region: ${{ secrets.AWS_DEFAULT_REGION_DEVOPSPROD }}
      k8s-role-to-assume: ${{ secrets.AWS_GITHUB_ROLE_DEVOPSPROD }}