name: Build and Deploy - Development

on:
  push:
    branches:
      - develop

jobs:
  deploy_on_k8s:
    uses: facily-tech/actions-reusable-workflows/.github/workflows/deploy-backend-api-argocd.yml@main
    with:
      tribe: logistic
      squad: wms
      vault-secret-path: logistic/wms/go-scaffold
      environment: production
      container-port: 8080      
      probe-readiness-path: /metrics
      probe-liveness-path: /metrics
      github-sha: ${{ github.sha }}
      repository-name: ${{ github.event.repository.name }}      
      application-name: ${{ github.event.repository.name }}
      application-domain: ${{ github.event.repository.name }}.faci.ly
    secrets:
      docker-build-extra-args: '-f build/Dockerfile'
      github-org: ${{ secrets.FACILY_ORG }}
      docker-registry: ${{ secrets.DOCKER_REGISTRY_PRODUCTION }}
      facily-github-token: ${{ secrets.FACILY_GITHUB_TOKEN }}
      ecr-aws-region: ${{ secrets.AWS_DEFAULT_REGION_PRODUCTION }}
      ecr-aws-role-to-assume: ${{ secrets.AWS_GITHUB_ROLE_PRODUCTION }}
      k8s-aws-region: ${{ secrets.AWS_DEFAULT_REGION_DEVOPSPROD }}
      k8s-role-to-assume: ${{ secrets.AWS_GITHUB_ROLE_DEVOPSPROD }}   
      argocd-username: ${{ secrets.ARGOCD_USERNAME }}
      argocd-password: ${{ secrets.ARGOCD_PASSWORD }}